publish_transform_node:
  ros__parameters:

    # Geoemtry parameters
    radius_rb1: 0.25
    large_shelf: 0.5

    frame_head_to_shelf: "robot_odom"
    distance_aproach_target_shelf: 0.05

bt_ros2_async:
  ros__parameters:
    #bt_xml: "approach_shelf.xml"
    #bt_xml: "find_station_and_init_local.xml"
    #bt_xml: "find_shelf_and_publish.xml"
    # bt_xml: "handler_shelf.xml"
    #bt_xml: "change_footprint.xml"
    #bt_xml: "behaviortree_entire.xml"
    #bt_xml: "find_shelf_and_nav.xml"
    #bt_xml: "find_shelf_and_turn_test.xml"
    #bt_xml: "carry_and_discharge_shelf.xml"
    bt_xml: "find_deep_shelf.xml"
    #bt_xml: "only_change_footprint.xml"